services:
  proxy:
    build: ./proxy
    image: gserraa/main:proxy
    container_name: proxy
    ports:
      - "80:80"

  web1:
    build: ./app
    image: gserraa/main:web1
    container_name: web1

  web2:
    build: ./app
    image: gserraa/main:web2
    container_name: web2

  db:
    build: ./db
    image: gserraa/main:db
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db_proj3
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/

  #database tester service
  adminer:
    image: adminer
    ports:
      - 8090:8080

volumes:
  db_data:
    name: global_db_volume
