services:
  proxy:
    build: ./proxy
    image: gserraa/main:proxy
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - web1


  web1:
    build: ./app
    image: gserraa/main:web1
    container_name: web1

  web2:
    build: ./app
    image: gserraa/main:web2
    container_name: web2

  db-primaria:
    build: ./db-primaria
    image: gserraa/main:db-primaria
    container_name: db-primaria
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db_proj3
    volumes:
      - db_data:/var/lib/postgresql/data

  db-replica:
    build: ./db-replica
    image: gserraa/main:db-replica
    container_name: db-replica
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    depends_on:
      - db-primaria

  #database tester service
  adminer:
    image: adminer
    ports:
      - 8090:8080

volumes:
  db_data:
    name: global_db_volume
